# Generated by Django 4.0.4 on 2022-05-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='该宏文件之功能代码', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Addon',
        ),
    ]
