# Generated by Django 4.0.4 on 2022-05-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmdm', '0002_addongeneral_delete_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addongeneral',
            name='code',
            field=models.CharField(help_text='功能代码', max_length=10),
        ),
    ]
