# Generated by Django 4.0.4 on 2022-05-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmdm', '0004_alter_akc_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='addongeneral',
            name='desc',
            field=models.CharField(default='', help_text='功能描述', max_length=20),
        ),
    ]
