# Generated by Django 4.0.4 on 2022-05-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmdm', '0005_addongeneral_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='akc',
            name='addon',
            field=models.ManyToManyField(to='hmdm.addongeneral'),
        ),
    ]
