# Generated by Django 4.0.4 on 2022-05-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmdm', '0006_akc_addon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akc',
            name='addon',
        ),
        migrations.AddField(
            model_name='akc',
            name='addon',
            field=models.CharField(choices=[('DM22005', '报警'), ('DM22009', '分别控制')], default='', max_length=10),
        ),
    ]
